services:
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3.11-alpine
    restart: always
    ports:
      - "5672:5672"

volumes:
  postgres_data:
