# Generated by Django 3.2.17 on 2023-02-13 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Snippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, default="Untitled", max_length=100),
                ),
                ("body", models.CharField(max_length=65536)),
                (
                    "syntax",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("bash", "Bash"),
                            ("c", "C"),
                            ("cpp", "C++"),
                            ("csharp", "C#"),
                            ("css", "CSS"),
                            ("go", "Go"),
                            ("haskell", "Haskell"),
                            ("html", "HTML"),
                            ("java", "Java"),
                            ("js", "JavaScript"),
                            ("json", "JSON"),
                            ("lua", "Lua"),
                            ("md", "Markdown"),
                            ("mysql", "MySQL"),
                            ("objc", "Objective-C"),
                            ("perl", "Perl"),
                            ("php", "PHP"),
                            ("postgres", "PostgreSQL"),
                            ("python", "Python"),
                            ("ruby", "Ruby"),
                            ("rust", "Rust"),
                            ("smalltalk", "Smalltalk"),
                            ("sql", "SQL"),
                            ("swift", "Swift"),
                            ("toml", "TOML"),
                            ("ts", "TypeScript"),
                            ("yaml", "YAML"),
                        ],
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expiration", models.DateTimeField(blank=True, null=True)),
                ("url", models.CharField(editable=False, max_length=8, unique=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snippets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
