# Generated by Django 3.2.17 on 2023-02-18 07:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="snippet",
            options={"ordering": ("-created_at",)},
        ),
    ]
